sudo: required
dist: xenial

language: python
cache: pip
before_install:
  - sudo apt-get install -y libopenmpi-dev
install:
  - pip install -r requirements.txt
  - pip install .
script:
  - pytest --expensive tests/

matrix:
  include:
  - name: "Linting"
    python: "3.7"
    install:
      - pip install -r requirements.txt
      - pip install -r requirements-dev.txt
      - pip install .
    script:
      - ci/lint.sh

  - name: "3.7 Coverage Tests"
    python: "3.7"
    script:
      - py.test --cov-report=xml --cov=${VIRTUAL_ENV}/lib/python3.7/site-packages/imitation --expensive tests/
    after_success:
      - mv .coverage .coverage.imitation
      - coverage combine  # rewrite paths
      - codecov

  - name: "3.7 Static Type Checking"
    python: "3.7"
    install:
      - pip install -r requirements.txt
      - pip install .
      - pip install pytype
    script:
      - ci/type_check.sh

  - name: "3.6 Unit Tests"
    python: "3.6"
  - name: "3.7 Unit Tests"
    python: "3.7"
